config/routes.rb
Rails.application.routes.draw do
  post 'messages/create'

  get 'messages/new'

  get 'messages/index'

  get 'home/index'
  devise_for :customers, controllers: {registrations: 'registrations'}

  root to: "home#index"
  resources :products do
    resources :issues
    resources :reviews
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :comment, length: { minimum: 20 }
  validates :status, inclusion: { in: %w(REPORTED INVESTIGATED FIX_IN_PROGRESS FIXED), message: "%{value} is not a valid severity level" }
  validates :severity, inclusion: { in: %w(COSMETIC MINOR MAJOR CRITICAL),
                                    message: "%{value} is not a valid severity level" }
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_product

   # GET /products/:product_id/issues
  # GET /products/:product_id/issues.json
  def index
    @issues = @product.issues
  end

  # GET /products/:product_id/issues/:id
  # GET /issues/:id.json
  def show
    @issue = @product.issues.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :show, status: :ok, location: @issue }
    end
  end


  # GET /products/:product_id/issues/new
  # GET /products/:product_id/issues/new.json
  def new
    @issue = @product.issues.build

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render json: @issue }
    end

  end

   # GET /products/:product_id/issues/:id/edit
  def edit
    @issue = @product.issues.find(params[:id])    
  end

  # POST /products/:product_id/issues
  # POST /products/:product_id/issues.json
  def create
    create_params = issue_params.merge({customer_id: current_customer.id})
    @issue = @product.issues.create(create_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to([@issue.product, @issue], :notice => 'Issue was successfully created.') }
        # the location key value is an array in order to build the correct route to the issue nested resource
        format.json { render json: @issue, status: :created, location: [@issue.product, @issue] }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /products/:product_id/issues/:id
  # PUT /products/:product_id/issues/:id.json
  def update
    @issue = @product.issues.find(params[:id])

    respond_to do |format|
    update_params = issue_params.merge({customer_id: current_customer.id})
      if @issue.update_attributes(update_params)
        format.html { redirect_to([@issue.product, @issue], :notice => 'Issue was successfully updated.') }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/:product_id/issues/:id
  # DELETE /products/:product_id/issues/:id.json
  def destroy
   
    @issue = @product.issues.find(params[:id])
    @issue.destroy

    respond_to do |format|
      #1st argument references the path /posts/:post_id/comments/
      format.html { redirect_to product_issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
       @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:severity, :comment)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for([@issue.product, @issue]) do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :severity %>
    <%= f.select :severity, %w(COSMETIC MINOR MAJOR CRITICAL) %>
  </div>
  <div class="field">
  <%= f.label :comment %><br>
  <%= f.text_area :comment, rows: 10, cols: 60 %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue for <%= @product.name %></h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', [@issue.product, @issue]  %> |
<%= link_to 'Back', product_issues_path(@issue.product) %>

app/views/issues/index.html.erb
<h1>Issues for <%= @product.name %></h1>
        <p>  <%= image_tag("#{@product.code}.jpg", alt: "#{@product.name}", class: 'product_image_index') %>   </p> 

<table>
  <thead>
    <tr>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>Severity</th>
      <th>Comment</th> 
      <th>Actions</th> 
    </tr>  
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.severity %></td>
        <td><%= issue.comment %></td>
          <td>
              <%= link_to 'Show', product_issue_path(issue.product, issue) %>
          </td>
          <% if current_customer.id == issue.customer.id%>
            <td>
                <%= link_to 'Edit', edit_product_issue_path(issue.product, issue) %>
            </td>
            <td><%= link_to 'Destroy', [issue.product, issue], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_product_issue_path %>
<span class='action_4'>
  <%= link_to 'Back to products', root_path %>
</span>

app/views/issues/new.html.erb
<h1>New Issue for <%= @product.name %></h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', product_issues_path(@issue.product)%>

app/views/issues/show.html.erb
<p>
  <b>Severity:</b>
  <%= @issue.severity %>
</p>

<p>
  <b>Comment:</b>
  <%= @issue.comment %>
</p>

<%= link_to 'Edit', edit_product_issue_path(@issue.product, @issue) %> |
<%= link_to 'Back', product_issues_path(@issue.product) %>