config/routes.rb
Rails.application.routes.draw do
  post 'messages/create'

  get 'messages/new'

  get 'messages/index'

  get 'home/index'
  devise_for :customers, controllers: {registrations: 'registrations'}

  root to: "home#index"
  resources :products do
    resources :issues
    resources :reviews
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_customer!, only: [:index, :new]

  def index
    @products = Product.all
  end

  def new
  end

  def edit
  end
end

app/helpers/home_helper.rb
module HomeHelper
   # Looks at the number of issues per severity and determines a ratings score
  #
  # @param Hash a count of all issues for the product, grouped per severity
  # 
  # @return Hash where key=severity, val=issue count
  def issue_ratings(count)
    return 0 if count.empty?
    return 5 if count['CRITICAL'] > 1
    return 4 if count['CRITICAL'] == 1
    return 3 if count['MAJOR'] > 1
    return 2 if count['MAJOR'] == 1
    return 1 if count['MINOR'] > 1
    return 1 if count['COSMETIC'] == 1 && count['MINOR'] == 1
    return 0
  end 
end

app/views/home/index.html.erb
<h1>Starhub Products</h1>

<div class="half_line">
  <p class="to_left">
      Logged in as: <%= current_customer.username %>
      <span id="review_notification" class="to_right flash"></span>
  </p>
</div>

<br>
<br>

<table>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('odd_line', 'even_line') %>">

      <td>
        <%= image_tag("#{product.code}.jpg", alt: "#{product.name}", class: 'product_image') %>
      </td>
      <td class='product_description'>
        <dl>
          <dt><%= product.name %></dt>
          <dt><%= product.category%></dt>
        </dl>
      </td>
      <td>
        <table class='paddingColumns'>
          <tr>
            <th>Reviews</th>
            <th>Issues</th> 
          </tr>
          <tr>
            <td>
              <% product.average_ratings.times do %>
                <%= image_tag('heart.png', alt: 'heart', class: 'rating_image') %>
              <% end %>
            </td> 
            <td>
              <% issue_ratings(product.issue_count).times do %>
                <%= image_tag('warning.png', alt: 'warning', class: 'rating_image') %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>               

            <%= link_to 'see all Reviews', product_reviews_path(product) %> 
            </td>
            <td>      
              <%= link_to 'See all Issues', product_issues_path(product) %>
            </td> 
          </tr>  
          <tr>
            <td>               
              <%= link_to 'Add a Review', new_product_review_path(product) %> 

            </td>
            <td>      
              <%= link_to 'Report an Issue',new_product_issue_path(product) %>
            </td> 
          </tr>
        </table>
      </td>      
      <td></td>
      <td class='product_actions'>
      <!-- we would enable these links only for admininstrators, not customers-->
        <%= link_to_if false, 'Edit', edit_product_path(product) %>
        <%= link_to_if false, 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- we would enable this link only for admininstrators, not customers-->
<%= link_to_if false, 'New Product', new_product_path, error: "Flash message" %>

<br>
<%= link_to "Log out", destroy_customer_session_path, method: :delete %>