config/routes.rb
Rails.application.routes.draw do
  post 'messages/create'

  get 'messages/new'

  get 'messages/index'

  get 'home/index'
  devise_for :customers, controllers: {registrations: 'registrations'}

  root to: "home#index"
  resources :products do
    resources :issues
    resources :reviews
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product

   # GET /products/:product_id/reviews
  # GET /products/:product_id/reviews.json
  def index
    @reviews = @product.reviews
  end

  # GET /products/:product_id/reviews/:id
  # GET /reviews/:id.json
  def show
    @review = @product.reviews.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :show, status: :ok, location: @review }
    end
  end


  # GET /products/:product_id/reviews/new
  # GET /products/:product_id/reviews/new.json
  def new
    @review = @product.reviews.build

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render json: @review }
    end

  end

   # GET /products/:product_id/reviews/:id/edit
  def edit
    @review = @product.reviews.find(params[:id])    
  end

  # POST /products/:product_id/reviews
  # POST /products/:product_id/reviews.json
  def create
    create_params = review_params.merge({customer_id: current_customer.id})
    @review = @product.reviews.create(create_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to([@review.product, @review], :notice => 'Review was successfully created.') }
        # the location key value is an array in order to build the correct route to the review nested resource
        format.json { render json: @review, status: :created, location: [@review.product, @review] }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /products/:product_id/reviews/:id
  # PUT /products/:product_id/reviews/:id.json
  def update
    @review = @product.reviews.find(params[:id])

    respond_to do |format|
    update_params = review_params.merge({customer_id: current_customer.id})
      if @review.update_attributes(update_params)
        format.html { redirect_to([@review.product, @review], :notice => 'Review was successfully updated.') }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/:product_id/reviews/:id
  # DELETE /products/:product_id/reviews/:id.json
  def destroy
   
    @review = @product.reviews.find(params[:id])
    @review.destroy

    respond_to do |format|
      #1st argument references the path /posts/:post_id/comments/
      format.html { redirect_to product_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
       @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@review.product, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, %w(1 2 3 4 5), prompt: '1 is worst, 5 is best' %>
  </div>
  <div class="field">
  <%= f.label :comment %><br>
  <%= f.text_area :comment, rows: 10, cols: 60 %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review for <%= @product.name %></h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', [@review.product, @review]  %> |
<%= link_to 'Back', product_reviews_path(@review.product) %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= @product.name %></h1>
        <p>  <%= image_tag("#{@product.code}.jpg", alt: "#{@product.name}", class: 'product_image_index') %>   </p> 

<table>
  <thead>
    <tr>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>Rating</th>
      <th>Comment</th> 
      <th>Actions</th> 
    </tr>  
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
          <td>
              <%= link_to 'Show', product_review_path(review.product, review) %>
          </td>
          <% if current_customer.id == review.customer.id%>
            <td>
                <%= link_to 'Edit', edit_product_review_path(review.product, review) %>
            </td>
            <td><%= link_to 'Destroy', [review.product, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_product_review_path %>
<span class='action_4'>
  <%= link_to 'Back to products', root_path %>
</span>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', product_reviews_path(@review.product)%>

app/views/reviews/show.html.erb
<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<span class="action_1">
  <%= link_to 'Back', product_reviews_path(@review.product) %>
</span>
<% if current_customer.id == @review.customer.id %>
  <span class="action_2">
    <%= link_to 'Edit', edit_product_review_path(@review.product, @review) %> 
  </span>
  <% else %>
  <span class="action_3">
    <%= link_to(image_tag("mail.png"),  
                    messages_new_path(params: {originator: current_customer,
                                              recipient: @review.customer}),
                    title: 'Send message to the reviewer',
                   data: { confirm: "You want to message the reviewer?" }) %>
  </span>
<% end %>

<span class="action_4">
  <%= link_to(image_tag("mailbox.png"),  
                  messages_index_path(params: {mailbox: current_customer}),
                  title: 'Read new messages',
                 data: { confirm: "You want to read new messages?" }) %>
</span>